# This is a basic workflow to help you get started with Actions

name: ci_build_kernel

on:
  workflow_dispatch:
    inputs:
      KERNEL_URL:
        description: 'kernel_url'
        required: true
        default: 'https://github.com/xiaocheng20/kernel_lge_sm8150.git'
      DEFCONFIG:
        description: 'defconfig'
        required: true
        default: 'flashlmdd_lao_com-perf_defconfig'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: checkout
      - uses: actions/checkout@v3

      - name: Cleanup workspace
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox* google* dotnet* powershell openjdk* php*
          sudo -E apt-get update
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          df -h

      - name: Setup python3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Setup environment
        run: |
          sudo apt-get install bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev libwxgtk3.0-dev
      
      
      - name: Clone kernel repo
        run: |
          git clone --recurse-submodules ${{ github.event.inputs.KERNEL_URL }} $GITHUB_WORKSPACE/kernel_source
          
          
      - name: Clone Toolchain
        run: |
         git https://github.com/xiaocheng20/Toolchain.git $GITHUB_WORKSPACE/kernel_source/Toolchain
         
      - name: Clone Toolchain
        run: |
          cd $GITHUB_WORKSPACE/kernel_source/Toolchain
          ls
          cp -af google_clang/* ../clang
          cp -af google_gcc/aarch64-linux-android-4.9/ ../gcc4.9
          cp -af google_gcc/arm-linux-androideabi-4.9/ ../gcc4.9_32
          cd ..
          ls gcc4.9
        
